# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               John Petitto
tagline:             Software Developer
url:                 http://www.johnpetitto.com
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John Petitto
  url:               https://github.com/jpetitto
  email:             john.petitto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jpetitto/jpetitto.github.io

# Navigation bar
pages_list:
  About: '/about'
  Resume: '/resume'
  Blog: '/blog'
